### ISSUE TITLE
Swagger.json Validation Issue

### ISSUE THREAD

**Issue by valllabh** [ocsf/ocsf-server#41]
When attempting to validate the Swagger.json file using the online Swagger Parser tool at https://apitools.dev/swagger-parser/online/, the validation process fails, indicating the validation log.
```
Swagger schema validation failed.
  #/info must NOT have additional properties
  #/info must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/schema must be object
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1enrich/post/parameters/2 must have required property 'type'
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1enrich/post/parameters/2 must have required property '$ref'
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2/schema must be object
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2 must have required property 'type'
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2 must have required property '$ref'
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0/schema must be object
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0 must have required property 'type'
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0 must have required property '$ref'
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf


Error: Swagger schema validation failed.
  #/info must NOT have additional properties
  #/info must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/schema must be object
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1enrich/post/parameters/2 must have required property 'type'
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1enrich/post/parameters/2 must have required property '$ref'
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2/schema must be object
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2 must have required property 'type'
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2 must have required property '$ref'
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0/schema must be object
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0 must have required property 'type'
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0 must have required property '$ref'
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf

    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:29:45042

SyntaxError: Swagger schema validation failed.
  #/info must NOT have additional properties
  #/info must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/schema must be object
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1enrich/post/parameters/2 must have required property 'type'
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1enrich/post/parameters/2 must have required property '$ref'
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1enrich/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2/schema must be object
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2/in must be equal to one of the allowed values
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2 must have required property 'type'
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1translate/post/parameters/2 must have required property '$ref'
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must NOT have additional properties
  #/paths/~1api~1translate/post/parameters/2 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0/schema must be object
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0/in must be equal to one of the allowed values
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0 must have required property 'type'
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf
  #/paths/~1api~1validate/post/parameters/0 must have required property '$ref'
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must NOT have additional properties
  #/paths/~1api~1validate/post/parameters/0 must match exactly one schema in oneOf

    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:6322)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3391)
```

**Comment by rmouritzen-splunk** [comment]
Fixed
